# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubevirt
from kubevirt.models.v1alpha1_virtual_machine_pool_list import V1alpha1VirtualMachinePoolList  # noqa: E501
from kubevirt.rest import ApiException


class TestV1alpha1VirtualMachinePoolList(unittest.TestCase):
    """V1alpha1VirtualMachinePoolList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1VirtualMachinePoolList(self):
        """Test V1alpha1VirtualMachinePoolList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubevirt.models.v1alpha1_virtual_machine_pool_list.V1alpha1VirtualMachinePoolList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
