# coding: utf-8

"""
    KubeVirt API

    This is KubeVirt API an add-on for Kubernetes.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: kubevirt-dev@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from kubevirt.configuration import Configuration


class V1alpha1VirtualMachinePoolScaleInStrategy(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'proactive': 'V1alpha1VirtualMachinePoolProactiveScaleInStrategy'
    }

    attribute_map = {
        'proactive': 'proactive'
    }

    def __init__(self, proactive=None, _configuration=None):  # noqa: E501
        """V1alpha1VirtualMachinePoolScaleInStrategy - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._proactive = None
        self.discriminator = None

        if proactive is not None:
            self.proactive = proactive

    @property
    def proactive(self):
        """Gets the proactive of this V1alpha1VirtualMachinePoolScaleInStrategy.  # noqa: E501

        Proactive scale-in by forcing VMs to shutdown during scale-in (Default)  # noqa: E501

        :return: The proactive of this V1alpha1VirtualMachinePoolScaleInStrategy.  # noqa: E501
        :rtype: V1alpha1VirtualMachinePoolProactiveScaleInStrategy
        """
        return self._proactive

    @proactive.setter
    def proactive(self, proactive):
        """Sets the proactive of this V1alpha1VirtualMachinePoolScaleInStrategy.

        Proactive scale-in by forcing VMs to shutdown during scale-in (Default)  # noqa: E501

        :param proactive: The proactive of this V1alpha1VirtualMachinePoolScaleInStrategy.  # noqa: E501
        :type: V1alpha1VirtualMachinePoolProactiveScaleInStrategy
        """

        self._proactive = proactive

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1VirtualMachinePoolScaleInStrategy, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1VirtualMachinePoolScaleInStrategy):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1VirtualMachinePoolScaleInStrategy):
            return True

        return self.to_dict() != other.to_dict()
